# TODO: Please fill in the appropriate information and rename this file as "config.yaml"
---
Server:
  RunMode: release
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
  HandleMethodNotAllowed: true
App:
  DefaultContextTimeout: 20 # sec
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: /static
  UploadImageMaxSize: 5  # MB  -- Web Server也要檔！
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
    - .gif
  UploadImageAllowMIME:
    - image/jpeg
    - image/jpg
    - image/gif
    - image/png
  UploadDocMaxSize: 20  # MB
  UploadDocAllowExts:
    - .pdf
  UploadDocAllowMIME:
    - application/pdf
Database:
  DBType: mysql
  UserName: # aaa - db username
  Password: # aaa123 - db password
  Host: 127.0.0.1:3306
  DBName: gin_blog
  TablePrefix: blog_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Auth:
  PBKDF2salt: # abc000111222333abc99988877ABC - Please generate a random number as the key
  JWTkey: # abcGGG99988877ABC111222333abc - Please generate a random number as the key
  JWTiss: khaos
  JWTexp: 600000 # 大約七天
Email:
  Host: smtp.gmail.com
  Port: 587 # 465
  From: # xxx@gmail.com
  UserName: # xxx@gmail.com
  Password: # pppppppp
  IsSSL: true
  To:
    - # yyy@gmail.com
    - # zzz@ntu.edu.tw
...