---
Server:
  # RunMode: debug
  RunMode: release
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
  HandleMethodNotAllowed: true
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: /static
  UploadImageMaxSize: 5  # MB  -- Web Server也要檔！
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
    - .gif
  UploadImageAllowMIME:
    - image/jpeg
    - image/jpg
    - image/gif
    - image/png
  UploadDocMaxSize: 20  # MB
  UploadDocAllowExts:
    - .pdf
  UploadDocAllowMIME:
    - application/pdf
Database:
  DBType: mysql
  UserName: kh
  Password: 1234
  Host: 127.0.0.1:3306
  DBName: gin_blog
  TablePrefix: blog_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Auth:
  PBKDF2salt: kGQcnzo5vfuJrnBhpc6V1EP7fAxqDI5Z
  JWTkey: 2M4o6UNzYD1qS9L1OXzskkusH3QIYyV1
  JWTiss: khaos
  JWTexp: 600000 # 大約七天
...